/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as FollowingRouteImport } from './routes/following'
import { Route as FeedDotxmlRouteImport } from './routes/feed[.]xml'
import { Route as ExternalRouteImport } from './routes/external'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthIndexRouteImport } from './routes/auth.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as UserUsernameRouteImport } from './routes/user.$username'
import { Route as TagTagRouteImport } from './routes/tag.$tag'
import { Route as PostPostIdRouteImport } from './routes/post.$postId'
import { Route as EmailUnsubscribeRouteImport } from './routes/email.unsubscribe'
import { Route as AuthAuthViewRouteImport } from './routes/auth.$authView'
import { Route as AdminEmailCampaignsRouteImport } from './routes/admin.email-campaigns'
import { Route as AdminSectionRouteImport } from './routes/admin.$section'
import { Route as AccountSettingsRouteImport } from './routes/account.settings'
import { Route as AccountPostsRouteImport } from './routes/account.posts'
import { Route as AccountSettingsIndexRouteImport } from './routes/account.settings.index'
import { Route as AccountPostsIndexRouteImport } from './routes/account.posts.index'
import { Route as SitemapsKindPageRouteImport } from './routes/sitemaps.$kind.$page'
import { Route as PostPostIdEditRouteImport } from './routes/post.$postId.edit'
import { Route as MediaUploadMediaIdRouteImport } from './routes/media.upload.$mediaId'
import { Route as MediaExternalImagePostIdRouteImport } from './routes/media.external-image.$postId'
import { Route as ApiStreamWebhookRouteImport } from './routes/api.stream.webhook'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AccountSettingsSettingsViewRouteImport } from './routes/account.settings.$settingsView'
import { Route as AccountPostsNewRouteImport } from './routes/account.posts.new'
import { Route as MediaVideoMediaIdThumbnailRouteImport } from './routes/media.video.$mediaId.thumbnail'
import { Route as MediaVideoMediaIdPlayerRouteImport } from './routes/media.video.$mediaId.player'
import { Route as MediaVideoMediaIdManifestRouteImport } from './routes/media.video.$mediaId.manifest'
import { Route as MediaVideoMediaIdDownloadRouteImport } from './routes/media.video.$mediaId.download'
import { Route as MediaPostPostIdCardRouteImport } from './routes/media.post.$postId.card'
import { Route as MediaImageMediaIdVariantRouteImport } from './routes/media.image.$mediaId.$variant'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowingRoute = FollowingRouteImport.update({
  id: '/following',
  path: '/following',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedDotxmlRoute = FeedDotxmlRouteImport.update({
  id: '/feed.xml',
  path: '/feed.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ExternalRoute = ExternalRouteImport.update({
  id: '/external',
  path: '/external',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const UserUsernameRoute = UserUsernameRouteImport.update({
  id: '/user/$username',
  path: '/user/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const TagTagRoute = TagTagRouteImport.update({
  id: '/tag/$tag',
  path: '/tag/$tag',
  getParentRoute: () => rootRouteImport,
} as any)
const PostPostIdRoute = PostPostIdRouteImport.update({
  id: '/post/$postId',
  path: '/post/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAuthViewRoute = AuthAuthViewRouteImport.update({
  id: '/$authView',
  path: '/$authView',
  getParentRoute: () => AuthRoute,
} as any)
const AdminEmailCampaignsRoute = AdminEmailCampaignsRouteImport.update({
  id: '/email-campaigns',
  path: '/email-campaigns',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSectionRoute = AdminSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => AdminRoute,
} as any)
const AccountSettingsRoute = AccountSettingsRouteImport.update({
  id: '/account/settings',
  path: '/account/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountPostsRoute = AccountPostsRouteImport.update({
  id: '/account/posts',
  path: '/account/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSettingsIndexRoute = AccountSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountSettingsRoute,
} as any)
const AccountPostsIndexRoute = AccountPostsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountPostsRoute,
} as any)
const SitemapsKindPageRoute = SitemapsKindPageRouteImport.update({
  id: '/sitemaps/$kind/$page',
  path: '/sitemaps/$kind/$page',
  getParentRoute: () => rootRouteImport,
} as any)
const PostPostIdEditRoute = PostPostIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => PostPostIdRoute,
} as any)
const MediaUploadMediaIdRoute = MediaUploadMediaIdRouteImport.update({
  id: '/media/upload/$mediaId',
  path: '/media/upload/$mediaId',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaExternalImagePostIdRoute =
  MediaExternalImagePostIdRouteImport.update({
    id: '/media/external-image/$postId',
    path: '/media/external-image/$postId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiStreamWebhookRoute = ApiStreamWebhookRouteImport.update({
  id: '/api/stream/webhook',
  path: '/api/stream/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSettingsSettingsViewRoute =
  AccountSettingsSettingsViewRouteImport.update({
    id: '/$settingsView',
    path: '/$settingsView',
    getParentRoute: () => AccountSettingsRoute,
  } as any)
const AccountPostsNewRoute = AccountPostsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AccountPostsRoute,
} as any)
const MediaVideoMediaIdThumbnailRoute =
  MediaVideoMediaIdThumbnailRouteImport.update({
    id: '/media/video/$mediaId/thumbnail',
    path: '/media/video/$mediaId/thumbnail',
    getParentRoute: () => rootRouteImport,
  } as any)
const MediaVideoMediaIdPlayerRoute = MediaVideoMediaIdPlayerRouteImport.update({
  id: '/media/video/$mediaId/player',
  path: '/media/video/$mediaId/player',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaVideoMediaIdManifestRoute =
  MediaVideoMediaIdManifestRouteImport.update({
    id: '/media/video/$mediaId/manifest',
    path: '/media/video/$mediaId/manifest',
    getParentRoute: () => rootRouteImport,
  } as any)
const MediaVideoMediaIdDownloadRoute =
  MediaVideoMediaIdDownloadRouteImport.update({
    id: '/media/video/$mediaId/download',
    path: '/media/video/$mediaId/download',
    getParentRoute: () => rootRouteImport,
  } as any)
const MediaPostPostIdCardRoute = MediaPostPostIdCardRouteImport.update({
  id: '/media/post/$postId/card',
  path: '/media/post/$postId/card',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaImageMediaIdVariantRoute =
  MediaImageMediaIdVariantRouteImport.update({
    id: '/media/image/$mediaId/$variant',
    path: '/media/image/$mediaId/$variant',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/cookie-policy': typeof CookiePolicyRoute
  '/external': typeof ExternalRoute
  '/feed.xml': typeof FeedDotxmlRoute
  '/following': typeof FollowingRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/account/posts': typeof AccountPostsRouteWithChildren
  '/account/settings': typeof AccountSettingsRouteWithChildren
  '/admin/$section': typeof AdminSectionRoute
  '/admin/email-campaigns': typeof AdminEmailCampaignsRoute
  '/auth/$authView': typeof AuthAuthViewRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/post/$postId': typeof PostPostIdRouteWithChildren
  '/tag/$tag': typeof TagTagRoute
  '/user/$username': typeof UserUsernameRoute
  '/admin/': typeof AdminIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/account/posts/new': typeof AccountPostsNewRoute
  '/account/settings/$settingsView': typeof AccountSettingsSettingsViewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stream/webhook': typeof ApiStreamWebhookRoute
  '/media/external-image/$postId': typeof MediaExternalImagePostIdRoute
  '/media/upload/$mediaId': typeof MediaUploadMediaIdRoute
  '/post/$postId/edit': typeof PostPostIdEditRoute
  '/sitemaps/$kind/$page': typeof SitemapsKindPageRoute
  '/account/posts/': typeof AccountPostsIndexRoute
  '/account/settings/': typeof AccountSettingsIndexRoute
  '/media/image/$mediaId/$variant': typeof MediaImageMediaIdVariantRoute
  '/media/post/$postId/card': typeof MediaPostPostIdCardRoute
  '/media/video/$mediaId/download': typeof MediaVideoMediaIdDownloadRoute
  '/media/video/$mediaId/manifest': typeof MediaVideoMediaIdManifestRoute
  '/media/video/$mediaId/player': typeof MediaVideoMediaIdPlayerRoute
  '/media/video/$mediaId/thumbnail': typeof MediaVideoMediaIdThumbnailRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/external': typeof ExternalRoute
  '/feed.xml': typeof FeedDotxmlRoute
  '/following': typeof FollowingRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/$section': typeof AdminSectionRoute
  '/admin/email-campaigns': typeof AdminEmailCampaignsRoute
  '/auth/$authView': typeof AuthAuthViewRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/post/$postId': typeof PostPostIdRouteWithChildren
  '/tag/$tag': typeof TagTagRoute
  '/user/$username': typeof UserUsernameRoute
  '/admin': typeof AdminIndexRoute
  '/auth': typeof AuthIndexRoute
  '/account/posts/new': typeof AccountPostsNewRoute
  '/account/settings/$settingsView': typeof AccountSettingsSettingsViewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stream/webhook': typeof ApiStreamWebhookRoute
  '/media/external-image/$postId': typeof MediaExternalImagePostIdRoute
  '/media/upload/$mediaId': typeof MediaUploadMediaIdRoute
  '/post/$postId/edit': typeof PostPostIdEditRoute
  '/sitemaps/$kind/$page': typeof SitemapsKindPageRoute
  '/account/posts': typeof AccountPostsIndexRoute
  '/account/settings': typeof AccountSettingsIndexRoute
  '/media/image/$mediaId/$variant': typeof MediaImageMediaIdVariantRoute
  '/media/post/$postId/card': typeof MediaPostPostIdCardRoute
  '/media/video/$mediaId/download': typeof MediaVideoMediaIdDownloadRoute
  '/media/video/$mediaId/manifest': typeof MediaVideoMediaIdManifestRoute
  '/media/video/$mediaId/player': typeof MediaVideoMediaIdPlayerRoute
  '/media/video/$mediaId/thumbnail': typeof MediaVideoMediaIdThumbnailRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/cookie-policy': typeof CookiePolicyRoute
  '/external': typeof ExternalRoute
  '/feed.xml': typeof FeedDotxmlRoute
  '/following': typeof FollowingRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/account/posts': typeof AccountPostsRouteWithChildren
  '/account/settings': typeof AccountSettingsRouteWithChildren
  '/admin/$section': typeof AdminSectionRoute
  '/admin/email-campaigns': typeof AdminEmailCampaignsRoute
  '/auth/$authView': typeof AuthAuthViewRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/post/$postId': typeof PostPostIdRouteWithChildren
  '/tag/$tag': typeof TagTagRoute
  '/user/$username': typeof UserUsernameRoute
  '/admin/': typeof AdminIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/account/posts/new': typeof AccountPostsNewRoute
  '/account/settings/$settingsView': typeof AccountSettingsSettingsViewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stream/webhook': typeof ApiStreamWebhookRoute
  '/media/external-image/$postId': typeof MediaExternalImagePostIdRoute
  '/media/upload/$mediaId': typeof MediaUploadMediaIdRoute
  '/post/$postId/edit': typeof PostPostIdEditRoute
  '/sitemaps/$kind/$page': typeof SitemapsKindPageRoute
  '/account/posts/': typeof AccountPostsIndexRoute
  '/account/settings/': typeof AccountSettingsIndexRoute
  '/media/image/$mediaId/$variant': typeof MediaImageMediaIdVariantRoute
  '/media/post/$postId/card': typeof MediaPostPostIdCardRoute
  '/media/video/$mediaId/download': typeof MediaVideoMediaIdDownloadRoute
  '/media/video/$mediaId/manifest': typeof MediaVideoMediaIdManifestRoute
  '/media/video/$mediaId/player': typeof MediaVideoMediaIdPlayerRoute
  '/media/video/$mediaId/thumbnail': typeof MediaVideoMediaIdThumbnailRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/cookie-policy'
    | '/external'
    | '/feed.xml'
    | '/following'
    | '/privacy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/account/posts'
    | '/account/settings'
    | '/admin/$section'
    | '/admin/email-campaigns'
    | '/auth/$authView'
    | '/email/unsubscribe'
    | '/post/$postId'
    | '/tag/$tag'
    | '/user/$username'
    | '/admin/'
    | '/auth/'
    | '/account/posts/new'
    | '/account/settings/$settingsView'
    | '/api/auth/$'
    | '/api/stream/webhook'
    | '/media/external-image/$postId'
    | '/media/upload/$mediaId'
    | '/post/$postId/edit'
    | '/sitemaps/$kind/$page'
    | '/account/posts/'
    | '/account/settings/'
    | '/media/image/$mediaId/$variant'
    | '/media/post/$postId/card'
    | '/media/video/$mediaId/download'
    | '/media/video/$mediaId/manifest'
    | '/media/video/$mediaId/player'
    | '/media/video/$mediaId/thumbnail'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cookie-policy'
    | '/external'
    | '/feed.xml'
    | '/following'
    | '/privacy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/$section'
    | '/admin/email-campaigns'
    | '/auth/$authView'
    | '/email/unsubscribe'
    | '/post/$postId'
    | '/tag/$tag'
    | '/user/$username'
    | '/admin'
    | '/auth'
    | '/account/posts/new'
    | '/account/settings/$settingsView'
    | '/api/auth/$'
    | '/api/stream/webhook'
    | '/media/external-image/$postId'
    | '/media/upload/$mediaId'
    | '/post/$postId/edit'
    | '/sitemaps/$kind/$page'
    | '/account/posts'
    | '/account/settings'
    | '/media/image/$mediaId/$variant'
    | '/media/post/$postId/card'
    | '/media/video/$mediaId/download'
    | '/media/video/$mediaId/manifest'
    | '/media/video/$mediaId/player'
    | '/media/video/$mediaId/thumbnail'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/cookie-policy'
    | '/external'
    | '/feed.xml'
    | '/following'
    | '/privacy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/account/posts'
    | '/account/settings'
    | '/admin/$section'
    | '/admin/email-campaigns'
    | '/auth/$authView'
    | '/email/unsubscribe'
    | '/post/$postId'
    | '/tag/$tag'
    | '/user/$username'
    | '/admin/'
    | '/auth/'
    | '/account/posts/new'
    | '/account/settings/$settingsView'
    | '/api/auth/$'
    | '/api/stream/webhook'
    | '/media/external-image/$postId'
    | '/media/upload/$mediaId'
    | '/post/$postId/edit'
    | '/sitemaps/$kind/$page'
    | '/account/posts/'
    | '/account/settings/'
    | '/media/image/$mediaId/$variant'
    | '/media/post/$postId/card'
    | '/media/video/$mediaId/download'
    | '/media/video/$mediaId/manifest'
    | '/media/video/$mediaId/player'
    | '/media/video/$mediaId/thumbnail'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  CookiePolicyRoute: typeof CookiePolicyRoute
  ExternalRoute: typeof ExternalRoute
  FeedDotxmlRoute: typeof FeedDotxmlRoute
  FollowingRoute: typeof FollowingRoute
  PrivacyRoute: typeof PrivacyRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  AccountPostsRoute: typeof AccountPostsRouteWithChildren
  AccountSettingsRoute: typeof AccountSettingsRouteWithChildren
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  PostPostIdRoute: typeof PostPostIdRouteWithChildren
  TagTagRoute: typeof TagTagRoute
  UserUsernameRoute: typeof UserUsernameRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiStreamWebhookRoute: typeof ApiStreamWebhookRoute
  MediaExternalImagePostIdRoute: typeof MediaExternalImagePostIdRoute
  MediaUploadMediaIdRoute: typeof MediaUploadMediaIdRoute
  SitemapsKindPageRoute: typeof SitemapsKindPageRoute
  MediaImageMediaIdVariantRoute: typeof MediaImageMediaIdVariantRoute
  MediaPostPostIdCardRoute: typeof MediaPostPostIdCardRoute
  MediaVideoMediaIdDownloadRoute: typeof MediaVideoMediaIdDownloadRoute
  MediaVideoMediaIdManifestRoute: typeof MediaVideoMediaIdManifestRoute
  MediaVideoMediaIdPlayerRoute: typeof MediaVideoMediaIdPlayerRoute
  MediaVideoMediaIdThumbnailRoute: typeof MediaVideoMediaIdThumbnailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/following': {
      id: '/following'
      path: '/following'
      fullPath: '/following'
      preLoaderRoute: typeof FollowingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed.xml': {
      id: '/feed.xml'
      path: '/feed.xml'
      fullPath: '/feed.xml'
      preLoaderRoute: typeof FeedDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/external': {
      id: '/external'
      path: '/external'
      fullPath: '/external'
      preLoaderRoute: typeof ExternalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/user/$username': {
      id: '/user/$username'
      path: '/user/$username'
      fullPath: '/user/$username'
      preLoaderRoute: typeof UserUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tag/$tag': {
      id: '/tag/$tag'
      path: '/tag/$tag'
      fullPath: '/tag/$tag'
      preLoaderRoute: typeof TagTagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/$postId': {
      id: '/post/$postId'
      path: '/post/$postId'
      fullPath: '/post/$postId'
      preLoaderRoute: typeof PostPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/$authView': {
      id: '/auth/$authView'
      path: '/$authView'
      fullPath: '/auth/$authView'
      preLoaderRoute: typeof AuthAuthViewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/admin/email-campaigns': {
      id: '/admin/email-campaigns'
      path: '/email-campaigns'
      fullPath: '/admin/email-campaigns'
      preLoaderRoute: typeof AdminEmailCampaignsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/$section': {
      id: '/admin/$section'
      path: '/$section'
      fullPath: '/admin/$section'
      preLoaderRoute: typeof AdminSectionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/account/settings': {
      id: '/account/settings'
      path: '/account/settings'
      fullPath: '/account/settings'
      preLoaderRoute: typeof AccountSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/posts': {
      id: '/account/posts'
      path: '/account/posts'
      fullPath: '/account/posts'
      preLoaderRoute: typeof AccountPostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/settings/': {
      id: '/account/settings/'
      path: '/'
      fullPath: '/account/settings/'
      preLoaderRoute: typeof AccountSettingsIndexRouteImport
      parentRoute: typeof AccountSettingsRoute
    }
    '/account/posts/': {
      id: '/account/posts/'
      path: '/'
      fullPath: '/account/posts/'
      preLoaderRoute: typeof AccountPostsIndexRouteImport
      parentRoute: typeof AccountPostsRoute
    }
    '/sitemaps/$kind/$page': {
      id: '/sitemaps/$kind/$page'
      path: '/sitemaps/$kind/$page'
      fullPath: '/sitemaps/$kind/$page'
      preLoaderRoute: typeof SitemapsKindPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/$postId/edit': {
      id: '/post/$postId/edit'
      path: '/edit'
      fullPath: '/post/$postId/edit'
      preLoaderRoute: typeof PostPostIdEditRouteImport
      parentRoute: typeof PostPostIdRoute
    }
    '/media/upload/$mediaId': {
      id: '/media/upload/$mediaId'
      path: '/media/upload/$mediaId'
      fullPath: '/media/upload/$mediaId'
      preLoaderRoute: typeof MediaUploadMediaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media/external-image/$postId': {
      id: '/media/external-image/$postId'
      path: '/media/external-image/$postId'
      fullPath: '/media/external-image/$postId'
      preLoaderRoute: typeof MediaExternalImagePostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stream/webhook': {
      id: '/api/stream/webhook'
      path: '/api/stream/webhook'
      fullPath: '/api/stream/webhook'
      preLoaderRoute: typeof ApiStreamWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/settings/$settingsView': {
      id: '/account/settings/$settingsView'
      path: '/$settingsView'
      fullPath: '/account/settings/$settingsView'
      preLoaderRoute: typeof AccountSettingsSettingsViewRouteImport
      parentRoute: typeof AccountSettingsRoute
    }
    '/account/posts/new': {
      id: '/account/posts/new'
      path: '/new'
      fullPath: '/account/posts/new'
      preLoaderRoute: typeof AccountPostsNewRouteImport
      parentRoute: typeof AccountPostsRoute
    }
    '/media/video/$mediaId/thumbnail': {
      id: '/media/video/$mediaId/thumbnail'
      path: '/media/video/$mediaId/thumbnail'
      fullPath: '/media/video/$mediaId/thumbnail'
      preLoaderRoute: typeof MediaVideoMediaIdThumbnailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media/video/$mediaId/player': {
      id: '/media/video/$mediaId/player'
      path: '/media/video/$mediaId/player'
      fullPath: '/media/video/$mediaId/player'
      preLoaderRoute: typeof MediaVideoMediaIdPlayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media/video/$mediaId/manifest': {
      id: '/media/video/$mediaId/manifest'
      path: '/media/video/$mediaId/manifest'
      fullPath: '/media/video/$mediaId/manifest'
      preLoaderRoute: typeof MediaVideoMediaIdManifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media/video/$mediaId/download': {
      id: '/media/video/$mediaId/download'
      path: '/media/video/$mediaId/download'
      fullPath: '/media/video/$mediaId/download'
      preLoaderRoute: typeof MediaVideoMediaIdDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media/post/$postId/card': {
      id: '/media/post/$postId/card'
      path: '/media/post/$postId/card'
      fullPath: '/media/post/$postId/card'
      preLoaderRoute: typeof MediaPostPostIdCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media/image/$mediaId/$variant': {
      id: '/media/image/$mediaId/$variant'
      path: '/media/image/$mediaId/$variant'
      fullPath: '/media/image/$mediaId/$variant'
      preLoaderRoute: typeof MediaImageMediaIdVariantRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminSectionRoute: typeof AdminSectionRoute
  AdminEmailCampaignsRoute: typeof AdminEmailCampaignsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminSectionRoute: AdminSectionRoute,
  AdminEmailCampaignsRoute: AdminEmailCampaignsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthRouteChildren {
  AuthAuthViewRoute: typeof AuthAuthViewRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAuthViewRoute: AuthAuthViewRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AccountPostsRouteChildren {
  AccountPostsNewRoute: typeof AccountPostsNewRoute
  AccountPostsIndexRoute: typeof AccountPostsIndexRoute
}

const AccountPostsRouteChildren: AccountPostsRouteChildren = {
  AccountPostsNewRoute: AccountPostsNewRoute,
  AccountPostsIndexRoute: AccountPostsIndexRoute,
}

const AccountPostsRouteWithChildren = AccountPostsRoute._addFileChildren(
  AccountPostsRouteChildren,
)

interface AccountSettingsRouteChildren {
  AccountSettingsSettingsViewRoute: typeof AccountSettingsSettingsViewRoute
  AccountSettingsIndexRoute: typeof AccountSettingsIndexRoute
}

const AccountSettingsRouteChildren: AccountSettingsRouteChildren = {
  AccountSettingsSettingsViewRoute: AccountSettingsSettingsViewRoute,
  AccountSettingsIndexRoute: AccountSettingsIndexRoute,
}

const AccountSettingsRouteWithChildren = AccountSettingsRoute._addFileChildren(
  AccountSettingsRouteChildren,
)

interface PostPostIdRouteChildren {
  PostPostIdEditRoute: typeof PostPostIdEditRoute
}

const PostPostIdRouteChildren: PostPostIdRouteChildren = {
  PostPostIdEditRoute: PostPostIdEditRoute,
}

const PostPostIdRouteWithChildren = PostPostIdRoute._addFileChildren(
  PostPostIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  CookiePolicyRoute: CookiePolicyRoute,
  ExternalRoute: ExternalRoute,
  FeedDotxmlRoute: FeedDotxmlRoute,
  FollowingRoute: FollowingRoute,
  PrivacyRoute: PrivacyRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  AccountPostsRoute: AccountPostsRouteWithChildren,
  AccountSettingsRoute: AccountSettingsRouteWithChildren,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  PostPostIdRoute: PostPostIdRouteWithChildren,
  TagTagRoute: TagTagRoute,
  UserUsernameRoute: UserUsernameRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiStreamWebhookRoute: ApiStreamWebhookRoute,
  MediaExternalImagePostIdRoute: MediaExternalImagePostIdRoute,
  MediaUploadMediaIdRoute: MediaUploadMediaIdRoute,
  SitemapsKindPageRoute: SitemapsKindPageRoute,
  MediaImageMediaIdVariantRoute: MediaImageMediaIdVariantRoute,
  MediaPostPostIdCardRoute: MediaPostPostIdCardRoute,
  MediaVideoMediaIdDownloadRoute: MediaVideoMediaIdDownloadRoute,
  MediaVideoMediaIdManifestRoute: MediaVideoMediaIdManifestRoute,
  MediaVideoMediaIdPlayerRoute: MediaVideoMediaIdPlayerRoute,
  MediaVideoMediaIdThumbnailRoute: MediaVideoMediaIdThumbnailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
